import { Toaster } from "react-hot-toast";
import "./globals.css";
import StyledComponentsRegistry from "./lib/registry";
import Providers from "./providers";
import { AuthProvider } from "./context/AuthContext";

export const metadata = {
  title: "marketna",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <AuthProvider>
        <Providers>
          <StyledComponentsRegistry>
            {children}
          </StyledComponentsRegistry>
        </Providers>

        {/* Toaster */}
        <Toaster position="top-left"  toastOptions={{
          style: {
            fontSize: "1.5rem",
            padding: "1.6rem 2rem",
            minWidth: "320px",
            zIndex:12
          },
        }}  />

      
        <div id="modal-root" />
        </AuthProvider>
      </body>
    </html>
  );
}